#!/usr/bin/env bash
#This script displays numbers from 1 to 100; displaying "FizzBuzz" when the number is a multiple of 3 and 5, "Fizz" when the number is a multiple of 3, "Buzz" when the number is a multiple of 5, and otherwise, just displaying the number.

i=1
while 	[ "$i" -le 100 ]
do 
	if [ $((i % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
