#!/usr/bin/env bash
#This script displays numbers from 1 to 100; displaying "FizzBuzz" when the number is a multiple of 3 and 5, "Fizz" when the number is a multiple of 3, "Buzz" when the number is a multiple of 5, and otherwise, just displaying the number.

i=1

