#!/usr/bin/env bash
#This script displays the content of /etc/passwd, only displaying Username, ID, and home directory path for the user.
file_h="etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d ":" -f1,3,6
done < "$file_h"
