#!/usr/bin/env bash
#This script displays "Best School" 10 times, but the 9th time it also displays "Hi" on a new line.
i=10
while [ "$i" -gt 0 ]
do
	echo "Best School"
	if [ "$i" -eq 2 ]
	then
		echo "Hi"
	fi
	i=$((i - 1))
done
i=$i
