#!/usr/bin/env bash
#This script displays the numbers 1 to 20 using the "while" loop and: displays "bad luck from China" after 4, "bad luck from Japan" after 9, and "bad luck from Italy" after 17.
i=1
while [ "$1" -le 20 ]
do
	echo "$i"
	case $1 in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	i=$((i + 1))
done
