#!/usr/bin/env bash
#This script creates /var/run/myscript.pid, displays "To infinity and beyond" indefinitely, displays "I hate the kill command" when SIGTERM, displays "Y U no love me?" when SIGINT, deletes /var/run/myscript.pid and termintates itself when SIGQUIT or SIGTERM.
sudo touch /var/run/myscript.pid
sudo bash -c "echo $$ > /var/run/myscript.pid"

trap interrup2 SIGINT
trap interrup1 SIGTERM
trap interrup3 SIGQUIT

interrup3()
{
	sudo rm /var/run/myscript.pid
	exit $?
}

interrup2()
{
	echo "Y U no love me?!"
}

interrup1()
{
	echo "I hate the kill command"
	sudo rm /var/run/myscript.pid
	exit $?
}

while true
do
	echo "To infinity and beyond"
	sleep .5
done
