#!/usr/bin/env bash
#This script displays "To infinity and beyond" with a sleep 2 in between each iteration.
trap interrupt SIGTERM

interrupt()
{
	echo "I am invincible!!!"
}

while true
do
	echo "To infinity and beyond"
	sleep 2
done
